kitty_mod ctrl+shift

clear_all_shortcuts yes

#: Clipboard {

#: Copy to clipboard

map --allow-fallback=shifted,ascii kitty_mod+c copy_to_clipboard

#: Paste from clipboard

map --allow-fallback=shifted,ascii kitty_mod+v paste_from_clipboard

#: }

#: Font sizes {

#: Increase font size

map kitty_mod+equal  change_font_size all +1.0
map kitty_mod+plus   change_font_size all +1.0

#: Decrease font size

map kitty_mod+minus       change_font_size all -1.0

#: Reset font size

map kitty_mod+backspace change_font_size all 0

#: }

#: Miscellaneous {

#: Command palette

map kitty_mod+f3 command_palette

#: Reload kitty.conf

map kitty_mod+f5 load_config_file

# Maximize

map f10 toggle_maximized

# Fullscreen

map f11 toggle_fullscreen

#: }
