[config]
version_check = false
caching = false

# Changing the syntax
# Expr is for keywords like {{ <keyword> }}
expr_prefix = "{{"
expr_postfix = "}}"

# Block is for stuff like for loops etc.
block_prefix = "<*"
block_postfix = "*>"

[config.wallpaper]
set = true
command = "awww img --transition-type random {{ image }}"

[templates.hyprland-conf]
input_path = "~/.config/matugen/templates/hyprland.conf"
output_path = "~/.config/hypr/colors.conf"

[templates.hyprland-lua]
input_path = "~/.config/matugen/templates/hyprland.lua"
output_path = "~/.config/hypr/colors.lua"

[templates.waybar]
input_path = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"
post_hook = "pkill -SIGUSR2 waybar"
