# leader key - ctrl+s
unbind C-b
set -g prefix C-s
bind C-a send-prefix

# vim keys
setw -g mode-keys vi

bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
bind -n 'M-\' select-pane -l

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# copy binds
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode-vi Escape send-keys -X cancel

# window
bind c new-window -c "#{pane_current_path}"
bind '\' split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# panes and window kill
unbind x
bind -r x killp
unbind &
bind -r C-x killw

source-file ~/.config/tmux/vim-split.conf
