# shell
set-option -g default-shell /usr/bin/fish

# mouse
set -g mouse on
set -g focus-events on

# Set terminal with proper colors
set -g default-terminal "tmux-256color"
set -as terminal-features ",xterm-256color:RGB"

# window and panes index
set -g base-index 1
setw -g pane-base-index 1
