$image = {{ image }}

<* for name, value in colors *>
${{ name }} = {{ value.default.rgba }}
<* endfor *>

$blur_primary = {{ colors.primary.default.rgba | set_alpha: 0.8}}

$blur_primary_container = {{ colors.primary_container.default.rgba | set_alpha: 0.4}}
